### ISSUE TITLE
Suggestion: API.

### ISSUE THREAD

**Issue by oskikiboy** [bstashio/bulma-customizer#2]
So I'm currently working on a site, and every-time I need to make a tweak I have to go back to the site and and regenerate, this can be a bit annoying. I was thinking of a simple api that allowed you to send the config and the options and receive a fully compiled css back (In whatever format you chose in the options).

Thanks!

**Comment by bstashio** [comment]
Definitely! That was the plan!

Unfortunately been too busy with other projects and wasn't able to find the time to finish it.

Thanks for the feedback!
