### ISSUE TITLE
Error importing extensions

### ISSUE THREAD

**Issue by go4cas** [bstashio/bulma-customizer#3]
When selecting one or more extensions, and building, the following error message appears:
"**Error: File to import not found or unreadable: ../repos/extensions/Wikiki/bulma-badge/badge.sass.**"

Building without the extensions works 100%.

**Comment by go4cas** [comment]
I have now tested with the "**Download Bundle**" option, and then it works.

**Comment by go4cas** [comment]
After closer inspection, although the build and download runs without error, all the extension folders are empty. I got things working, by using customizer to create a custom base bulma build, and then manlally installing and re-building the extensions.

**Comment by bstashio** [comment]
Sorry for the late response.

I'll take a look at it as soon as I find some free time.

Thanks for reporting it.
